version: '3.0'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    image: nginx:1.20
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/conf.d/
      - ./requirements/nginx/tools/hselbi.42.fr.crt:/etc/nginx/ssl/hselbi.42.fr.crt
      - ./requirements/nginx/tools/hselbi.42.fr.key:/etc/nginx/ssl/hselbi.42.fr.key
      - wp-volume:/var/www/wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:10.11
    container_name: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    environment:
      - DB_NAME: ${DB_NAME}
      - DB_USER: ${DB_USER}
      - DB_PASSWORD: ${DB_PASSWORD}
      - DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks: 
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    depends_on: 
      - mariadb
    volumes:
      - wp-volume:/var/www/wordpress
    env_file:
      - .env
    environment:
      - DB_NAME: ${DB_NAME}
      - DB_USER: ${DB_USER}
      - DB_PASSWORD: ${DB_PASSWORD}
      - DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - inception
    restart: always
  
  ftp-server:
    build: requirements/bonus/ftp-server
    container_name: ftp-server
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/wordpress
    networks:
     - project
    restart: always
    environment:
      FTP_USR: ${FTP_USR}
      FTP_PWD: ${FTP_PWD}

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge